name: "ant"
 
on:
  push:
    branches: [ $default-branch ]
  schedule:
    - cron: "1 9,10,11,12,13,14,15,16,17,18,19,20,21 * * *"
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ant/requirements.txt
    - name: running
      run: python ant/ant.py
